[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmd = 'npm ci --include=dev && npm install vite esbuild @vitejs/plugin-react autoprefixer postcss tailwindcss typescript --save'

[phases.build]
cmd = 'npm run build'

[start]
cmd = 'npm run start'